export const API_ENDPOINTS = {
  LOGIN: "/auth/login",
  REFRESH: "/auth/refresh",
  LOGIN_GOOGLE: "/auth/google",
  WORKSPACE: "/workspace",
  PROJECT: "/project",
  TASK: "/task",
  COMMENT: "/comment",
  DOCUMENTATION: "/documentation",
  PROJECT_ACCESS: "/project-access",
  WORKSPACE_MEMBER: "/workspace-member",
  INVITATION_SEND: "/invitation/send",

  WORKSPACE_BY_ID: (id: string) => `/workspace/${id}`,
  TASK_BY_ID: (id: string) => `/task/${id}/`,
  TASK_BY_PROJECT_ID: (projectId: string) => `/task/project/${projectId}`,
  TASK_BY_USER_ID: (userId: string) => `/task/user/${userId}`,
  CREATE_TASK: (projectId: string) => `/task/${projectId}`,
  EDIT_TASK_BY_ID: ( projectId: string, id: string) => `/task/${projectId}/${id}/`,
  DELETE_TASK_BY_ID: ( projectId: string, id: string) => `/task/${projectId}/${id}/`,
  PROJECT_BY_WORKSPACE_ID: (workpaceId: string) => `/project/${workpaceId}`,
  PROJECT_ACCESS_BY_ID: (id: string) => `/project-access/${id}`,
  WORKSPACE_MEMBER_BY_ID: (id: string) => `/workspace-member/${id}`,
  WORKSPACE_MEMBER_BY_WORKSPACE_ID: (workspaceId: string) => `/workspace-member/${workspaceId}`,
  ACTIVITY_BY_PROJECT_ID: (projectId: string) => `/activity/project/${projectId}`,
  COMMENT_BY_PROJECT_ID: (projectId: string) => `/comment/project/${projectId}`,
  PROJECT_OVERVIEW: (workspaceId: string, projectId: string) => `/project/overview/${workspaceId}/${projectId}`,
};